# Sample .env file
# DBPASSWD=password
# DBADMINERPORT=64901
# WEB_PORT=64801
# WEB_FILES=/path
# PROXY_PORT=443
# ADMINUSER=a@l.c
# ADMINPASS=password

# docker-compose down; docker-compose up --build -d; docker-compose logs -f

version: '2'
services:
  db:
    image: mariadb
    environment:
      - "MYSQL_USER=koel"
      - "MYSQL_PASSWORD=${DBPASSWD}"
      - "MYSQL_ROOT_PASSWORD=${DBPASSWD}"
    restart: always
  adminer:
    image: adminer
    restart: always
    ports:
      - "${DBADMINERPORT}:8080"
    environment:
      - ADMINER_DESIGN=lucas-sandery
      - ADMINER_PLUGINS=tables-filter tinymce
    links:
      - db
  web:
    build: .
    environment:
      - PROXY_PORT
      - DBPASSWD
      - ADMINUSER
      - ADMINPASS
    ports:
      - "${WEB_PORT}:443"
    volumes:
      - "${WEB_FILES}:/files"
    # restart: always
    links:
      - db
