#!/usr/bin/env python3
"""
Retrieve latest stable 'standard' x86_64 ISO URL from https://alpinelinux.org/downloads/
Uses only Python standard library.

This file was generated by AI on 2026-04-03.
"""

from html.parser import HTMLParser
from urllib.request import urlopen, Request
from urllib.parse import urljoin
import re

DOWNLOADS_URL = "https://alpinelinux.org/downloads/"

class DownloadsParser(HTMLParser):
    def __init__(self):
        super().__init__()
        self.in_standard_section = False
        self.capture_href = False
        self.links = []
        self._buffer = ""

    def handle_starttag(self, tag, attrs):
        attrs = dict(attrs)
        if tag == "h2" and attrs.get("id","").lower().startswith("standard"):
            # Some pages may have an id or an h2 with text "Standard"
            self.in_standard_section = True
        if self.in_standard_section and tag == "a" and "href" in attrs:
            href = attrs["href"]
            self.links.append(href)

    def handle_endtag(self, tag):
        if tag == "section" and self.in_standard_section:
            # assume section end ends standard block
            self.in_standard_section = False

    def handle_data(self, data):
        # fallback: detect a heading text "Standard" to start capturing
        if data.strip().lower() == "standard":
            self.in_standard_section = True

def fetch_html(url: str = DOWNLOADS_URL):
    req = Request(url, headers={"User-Agent":"python-urllib/3"})
    with urlopen(req, timeout=20) as r:
        return r.read().decode(r.headers.get_content_charset("utf-8"), errors="replace")

def find_latest_standard_x86_64_iso(downloads_html):
    parser = DownloadsParser()
    parser.feed(downloads_html)

    # fallback: also scan whole page for links matching standard x86_64 ISO filenames
    candidates = set(parser.links)
    # Add any hrefs found in raw HTML via regex
    for m in re.finditer(r'href=["\']([^"\']+)["\']', downloads_html, re.IGNORECASE):
        candidates.add(m.group(1))

    # Candidate pattern: contains "alpine-standard", "x86_64" and ".iso"
    pattern = re.compile(r'(^|/)(alpine-standard-[0-9]+\.[0-9]+\.[0-9]+-x86_64\.iso)$', re.IGNORECASE)
    versioned = []
    for href in candidates:
        # normalize possible full URLs or relative paths
        name = href.rstrip("/").split("/")[-1]
        m = pattern.search(href) or pattern.search(name)
        if m:
            # extract version numbers for sorting
            ver = re.search(r'([0-9]+)\.([0-9]+)\.([0-9]+)', name)
            if ver:
                version = tuple(int(x) for x in ver.groups())
                versioned.append((version, href))

    if not versioned:
        # fallback: looser pattern: alpine-standard-...-x86_64.iso
        loose = []
        p2 = re.compile(r'alpine-standard-([0-9][^/]*?)-x86_64\.iso', re.IGNORECASE)
        for href in candidates:
            m = p2.search(href)
            if m:
                # try to parse first numeric triplet in the group
                verm = re.search(r'([0-9]+(?:\.[0-9]+)+)', m.group(1))
                if verm:
                    parts = [int(x) for x in verm.group(1).split(".")[:3]]
                    while len(parts) < 3:
                        parts.append(0)
                    loose.append((tuple(parts), href))
        versioned = loose

    if not versioned:
        raise RuntimeError("No alpine-standard x86_64 ISO links found on page")

    # choose max version
    versioned.sort(key=lambda x: x[0], reverse=True)
    best_href = versioned[0][1]

    # build absolute URL if needed
    final = urljoin(DOWNLOADS_URL, best_href)
    return final

if __name__ == "__main__":
    html = fetch_html()
    url = find_latest_standard_x86_64_iso(html)
    print(url)
